const URL = "https://angularcommercewebsite-petproj-default-rtdb.firebaseio.com/.json";
const addButton = document.getElementById("fetch");

addButton.addEventListener("click", () => {
  fetch(URL, {
    method: "PUT",
    body: JSON.stringify({
      CATALOG: {
        dining: [
          {
            sofas: [
              {
                id: 0,
                SKU: "SS001",
                name: "Asgard Sofa",
                price: 250,
                rating: 4.5,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["L", "XL", "XS"],
                reviews: [],
                color: ["#816DFA", "#000000", "#B88E2F"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "SS002",
                name: "Valhalla Sofa",
                price: 320,
                rating: 4.8,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["M", "L", "XL"],
                reviews: [],
                color: ["#FFFFFF", "#C0C0C0", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "SS003",
                name: "Odin Sofa",
                price: 280,
                rating: 4.3,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["S", "M", "L"],
                reviews: [],
                color: ["#8B0000", "#B88E2F", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
            chairs: [
              {
                id: 0,
                SKU: "SS004",
                name: "Nordic Chair",
                price: 120,
                rating: 4.6,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["M", "L"],
                reviews: [],
                color: ["#000000", "#D3D3D3"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "SS005",
                name: "Loki Chair",
                price: 140,
                rating: 4.4,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["S", "M"],
                reviews: [],
                color: ["#FFD700", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "SS006",
                name: "Freya Chair",
                price: 160,
                rating: 4.7,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["M", "L"],
                reviews: [],
                color: ["#FF69B4", "#B88E2F", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
            tables: [
              {
                id: 0,
                SKU: "SS007",
                name: "Midgard Table",
                price: 450,
                rating: 4.9,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["M", "L", "XL"],
                reviews: [],
                color: ["#8B4513", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "SS008",
                name: "Thor Table",
                price: 520,
                rating: 4.8,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["XL"],
                reviews: [],
                color: ["#000000", "#B88E2F"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "SS009",
                name: "Frigg Table",
                price: 380,
                rating: 4.5,
                content: "...",
                description1: "...",
                description2: "...",
                additionalInformation: "...",
                size: ["S", "M"],
                reviews: [],
                color: ["#FFFFFF", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
          },
        ],
        living: [
          {
            sofas: [
              {
                id: 0,
                SKU: "LS001",
                name: "Zenith Sofa",
                price: 600,
                rating: 4.9,
                content: "Luxury meets comfort in this premium sofa.",
                description1: "Spacious seating with modern elegance.",
                description2: "Perfect for living rooms with a modern look.",
                additionalInformation: "Removable covers, stain-resistant fabric.",
                size: ["L", "XL"],
                reviews: [],
                color: ["#000000", "#808080"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "LS002",
                name: "Aurora Sofa",
                price: 550,
                rating: 4.7,
                content: "Elegant sofa for stylish living rooms.",
                description1: "Aurora adds lightness and comfort.",
                description2: "Cushioned for long-lasting relaxation.",
                additionalInformation: "Eco-friendly materials used.",
                size: ["M", "L"],
                reviews: [],
                color: ["#B88E2F", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "LS003",
                name: "Eclipse Sofa",
                price: 700,
                rating: 5,
                content: "Modern statement sofa with bold lines.",
                description1: "Stylish sofa with ergonomic design.",
                description2: "Perfect centerpiece for a modern home.",
                additionalInformation: "Durable steel frame.",
                size: ["XL"],
                reviews: [],
                color: ["#000000", "#8B0000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
            chairs: [
              {
                id: 0,
                SKU: "LC001",
                name: "Atlas Chair",
                price: 180,
                rating: 4.5,
                content: "Compact yet strong chair for daily use.",
                description1: "Durable wooden frame with modern design.",
                description2: "Perfect for any living room decor.",
                additionalInformation: "Stackable design saves space.",
                size: ["S", "M"],
                reviews: [],
                color: ["#000000", "#FFFFFF"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "LC002",
                name: "Helios Chair",
                price: 220,
                rating: 4.6,
                content: "Elegant living chair with soft cushioning.",
                description1: "Designed for comfort with fabric seating.",
                description2: "Ideal companion for coffee tables.",
                additionalInformation: "Durable and lightweight.",
                size: ["M", "L"],
                reviews: [],
                color: ["#FFD700", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "LC003",
                name: "Eos Chair",
                price: 200,
                rating: 4.4,
                content: "Minimalist design with durable materials.",
                description1: "Eos Chair offers modern simplicity.",
                description2: "Light and strong, easy to move.",
                additionalInformation: "Non-slip legs.",
                size: ["M"],
                reviews: [],
                color: ["#000000", "#C0C0C0"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
            tables: [
              {
                id: 0,
                SKU: "LT001",
                name: "Orion Table",
                price: 620,
                rating: 4.8,
                content: "Round living table with modern charm.",
                description1: "Perfect centerpiece for any living space.",
                description2: "Durable yet elegant design.",
                additionalInformation: "Made of engineered oak.",
                size: ["M", "L"],
                reviews: [],
                color: ["#8B4513", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "LT002",
                name: "Horizon Table",
                price: 750,
                rating: 5,
                content: "Bold rectangular table for family living.",
                description1: "Large surface for gatherings.",
                description2: "Built for durability and style.",
                additionalInformation: "Scratch-resistant finish.",
                size: ["XL"],
                reviews: [],
                color: ["#000000", "#B88E2F"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "LT003",
                name: "Nova Table",
                price: 500,
                rating: 4.7,
                content: "Compact square table, perfect for apartments.",
                description1: "Small but practical design.",
                description2: "Ideal for modern urban spaces.",
                additionalInformation: "Easy to clean surface.",
                size: ["S", "M"],
                reviews: [],
                color: ["#FFFFFF", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
          },
        ],
        bedroom: [
          {
            sofas: [
              {
                id: 0,
                SKU: "BS001",
                name: "Dream Sofa",
                price: 400,
                rating: 4.5,
                content: "Soft and cozy, perfect for bedrooms.",
                description1: "Dream Sofa offers comfort for relaxation.",
                description2: "Compact and space-saving.",
                additionalInformation: "Removable covers.",
                size: ["S", "M"],
                reviews: [],
                color: ["#000000", "#B88E2F"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "BS002",
                name: "Serenity Sofa",
                price: 450,
                rating: 4.7,
                content: "Elegant sofa for cozy bedroom corners.",
                description1: "Serenity brings elegance with comfort.",
                description2: "Upholstered in soft-touch fabric.",
                additionalInformation: "Durable wooden frame.",
                size: ["M", "L"],
                reviews: [],
                color: ["#808080", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "BS003",
                name: "Luna Sofa",
                price: 500,
                rating: 4.8,
                content: "Modern bedroom sofa with clean lines.",
                description1: "Compact yet stylish.",
                description2: "Perfect for reading corners or small bedrooms.",
                additionalInformation: "Sturdy wooden frame.",
                size: ["M", "L"],
                reviews: [],
                color: ["#FFFFFF", "#B88E2F"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
            chairs: [
              {
                id: 0,
                SKU: "BC001",
                name: "Selene Chair",
                price: 180,
                rating: 4.5,
                content: "Cozy bedroom chair.",
                description1: "Compact and cushioned.",
                description2: "Perfect for small bedroom spaces.",
                additionalInformation: "Fabric resists stains.",
                size: ["S", "M"],
                reviews: [],
                color: ["#000000", "#FFFFFF"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "BC002",
                name: "Aurora Chair",
                price: 200,
                rating: 4.6,
                content: "Stylish chair with soft seating.",
                description1: "Comfortable for reading.",
                description2: "Compact and lightweight.",
                additionalInformation: "Durable and easy to move.",
                size: ["M"],
                reviews: [],
                color: ["#FFD700", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "BC003",
                name: "Luna Chair",
                price: 220,
                rating: 4.7,
                content: "Elegant bedroom chair.",
                description1: "Stylish and comfortable.",
                description2: "Perfect for bedroom corners.",
                additionalInformation: "Lightweight and durable.",
                size: ["M", "L"],
                reviews: [],
                color: ["#000000", "#808080"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
            tables: [
              {
                id: 0,
                SKU: "BT001",
                name: "Sol Table",
                price: 350,
                rating: 4.5,
                content: "Small bedroom table.",
                description1: "Compact and practical.",
                description2: "Perfect for nightstands.",
                additionalInformation: "Sturdy and easy to clean.",
                size: ["S", "M"],
                reviews: [],
                color: ["#8B4513", "#000000"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 1,
                SKU: "BT002",
                name: "Luna Table",
                price: 400,
                rating: 4.6,
                content: "Elegant bedroom table.",
                description1: "Small yet stylish.",
                description2: "Perfect for reading corners.",
                additionalInformation: "Easy to move and clean.",
                size: ["M"],
                reviews: [],
                color: ["#FFFFFF", "#B88E2F"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
              {
                id: 2,
                SKU: "BT003",
                name: "Aurora Table",
                price: 450,
                rating: 4.7,
                content: "Modern bedroom table.",
                description1: "Compact and elegant.",
                description2: "Functional for small spaces.",
                additionalInformation: "Sturdy and durable.",
                size: ["M", "L"],
                reviews: [],
                color: ["#000000", "#808080"],
                img: ["/assets/img/Asgard sofa 1.png", "/assets/img/Asgard sofa 2.png", "/assets/img/Asgard sofa 3.png", "/assets/img/Asgard sofa 4.png", "/assets/img/Asgard sofa 5.png"],
              },
            ],
          },
        ],
      },
    }),
  });
});
